name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: NuGet
      run: nuget restore
    - name: Get TShock libs
      run: |
        curl -fsSLJo TShock.zip https://github.com/Pryaxis/TShock/releases/download/v4.4.0-pre15/TShock4.4.0_Pre15_Terraria1.4.1.2.zip
        7z e TShock.zip -olib\ OTAPI.dll TerrariaServer.exe TShockAPI.dll -r
    - name: Build
      run: msbuild /p:Configuration=Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: TShockPrometheus
        path: |
          TShockPrometheus/bin/x86/Release/net462/
          !TShockPrometheus/bin/x86/Release/net462/OTAPI.dll
          !TShockPrometheus/bin/x86/Release/net462/TerrariaServer.exe
          !TShockPrometheus/bin/x86/Release/net462/TShockAPI.dll
